[conformance_class]
.AI_Label
====
[%metadata]
identifier:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/ailabel
target:: /req/ailabel
inherit:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/base/xmlbasetype
inherit:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/base/geospatialtype
abstract-test:: /conf/ailabel/label
abstract-test:: /conf/ailabel/scenelabel
abstract-test:: /conf/ailabel/objectlabel
abstract-test:: /conf/ailabel/pixellabel
abstract-test:: /conf/ailabel/imageformatcode
====

[abstract_test]
====
[%metadata]
identifier:: /conf/ailabel/label
target:: /req/ailabel/label
test-purpose:: Verify that instance documents using the AI_Label XML elements listed in <<table-ai-label-properties>> validate against the XML schema specified in http://schemas.opengis.net/trainingdml-ai/part3/1.0/ai_label.xsd.
test-method:: Validate the instance document against the ai_label.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/ailabel/scenelabel
target:: /req/ailabel/scenelabel
test-purpose:: Verify that instance documents using the AI_SceneLabel XML elements listed in <<table-ai-scenelabel-properties>> validate against the XML schema specified in http://schemas.opengis.net/trainingdml-ai/part3/1.0/ai_sceneLabel.xsd.
test-method:: Validate the instance document against the ai_sceneLabel.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/ailabel/objectlabel
target:: /req/ailabel/objectlabel
test-purpose:: Verify that instance documents using the AI_ObjectLabel XML elements listed in <<table-ai-objectlabel-properties>> validate against the XML schema specified in http://schemas.opengis.net/trainingdml-ai/part3/1.0/ai_objectLabel.xsd.
test-method:: Validate the instance document against the ai_objectLabel.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/ailabel/pixellabel
target:: /req/ailabel/pixellabel
test-purpose:: Verify that instance documents using the AI_PixelLabel XML elements listed in <<table-ai-pixellabel-properties>> validate against the XML schema specified in http://schemas.opengis.net/trainingdml-ai/part3/1.0/ai_pixelLabel.xsd.
test-method:: Validate the instance document against the ai_pixelLabel.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/ailabel/imageformatcode
target:: /req/ailabel/imageformatcode
test-purpose:: Verify that instance documents using the AI_ImageFormatCode XML elements conform to the requirements specified by the Multipurpose Internet Mail Extensions (MIME) Part Two: Media Types https://www.ietf.org/rfc/rfc2046.txt[RFC 2046].
test-method:: Inspect the instance document to verify the above requirement.
====
