[conformance_class]
.AI_Labeling
====
[%metadata]
identifier:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/ailabeling
target:: /req/ailabeling
inherit:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/base/xmlbasetype
inherit:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/base/isometadatatype
abstract-test:: /conf/ailabeling/labeling
abstract-test:: /conf/ailabeling/labeler
abstract-test:: /conf/ailabeling/labelingprocedure
abstract-test:: /conf/ailabeling/labelingmethodcode
====

[abstract_test]
====
[%metadata]
identifier:: /conf/ailabeling/labeling
target:: /req/ailabeling/labeling
test-purpose:: Verify that instance documents using the AI_Labeling XML elements listed in <<table-ai-labeling-properties>> validate against the XML schema specified in http://schemas.opengis.net/trainingdml-ai/part3/1.0/ai_labeling.xsd.
test-method:: Validate the instance document against the ai_labeling.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/ailabeling/labeler
target:: /req/ailabeling/labeler
test-purpose:: Verify that instance documents using the AI_Labeler XML elements listed in <<table-ai-labeler-properties>> validate against the XML schema specified in http://schemas.opengis.net/trainingdml-ai/part3/1.0/ai_labeler.xsd.
test-method:: Validate the instance document against the ai_labeler.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/ailabeling/labelingprocedure
target:: /req/ailabeling/labelingprocedure
test-purpose:: Verify that instance documents using the AI_LabelingProcedure XML elements listed in <<table-ai-labelingprocedure-properties>> validate against the XML schema specified in http://schemas.opengis.net/trainingdml-ai/part3/1.0/ai_labelingProcedure.xsd.
test-method:: Validate the instance document against the ai_labelingProcedure.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/ailabeling/labelingmethodcode
target:: /req/ailabeling/labelingmethodcode
test-purpose:: Verify that instance documents using the AI_LabelingMethodCode XML elements validate against the XML schema specified in http://schemas.opengis.net/trainingdml-ai/part3/1.0/ai_labelingMethodCode.xsd.
test-method:: Validate the instance document against the ai_labelingMethodCode.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====
