[conformance_class]
.ISO Metadata Type
====
[%metadata]
identifier:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/base/isometadatatype
target:: /req/base/isometadatatype
abstract-test:: /conf/base/isometadatatype/band
abstract-test:: /conf/base/isometadatatype/extent
abstract-test:: /conf/base/isometadatatype/citation
abstract-test:: /conf/base/isometadatatype/scope
abstract-test:: /conf/base/isometadatatype/referencesystem
abstract-test:: /conf/base/isometadatatype/lineage
abstract-test:: /conf/base/isometadatatype/resolution
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/isometadatatype/band
target:: /req/base/isometadatatype/band
test-purpose:: Verify that instance documents using the MD_Band XML elements validate against the XML schema specified in https://schemas.isotc211.org/19115/-1/mrc/1.3.0/content.xsd.
test-method:: Validate the instance document against the content.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/isometadatatype/extent
target:: /req/base/isometadatatype/extent
test-purpose:: Verify that instance documents using the EX_Extent XML elements validate against the XML schema specified in https://schemas.isotc211.org/19115/-1/gex/1.3.0/extent.xsd.
test-method:: Validate the instance document against the extent.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/isometadatatype/citation
target:: /req/base/isometadatatype/citation
test-purpose:: Verify that instance documents using the CI_Citation XML elements validate against the XML schema specified in https://schemas.isotc211.org/19115/-1/cit/1.3.0/citation.xsd.
test-method:: Validate the instance document against the citation.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/isometadatatype/scope
target:: /req/base/isometadatatype/scope
test-purpose:: Verify that instance documents using the MD_Scope XML elements validate against the XML schema specified in https://schemas.isotc211.org/19115/-1/mcc/1.3.0/commonClasses.xsd.
test-method:: Validate the instance document against the commonClasses.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/isometadatatype/referencesystem
target:: /req/base/isometadatatype/referencesystem
test-purpose:: Verify that instance documents using the MD_ReferenceSystem XML elements validate against the XML schema specified in https://schemas.isotc211.org/19115/-1/mcc/1.3.0/referenceSystem.xsd.
test-method:: Validate the instance document against the commonClasses.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/isometadatatype/lineage
target:: /req/base/isometadatatype/lineage
test-purpose:: Verify that instance documents using the LI_Lineage XML elements validate against the XML schema specified in https://schemas.isotc211.org/19115/-1/mcc/1.3.0/lineage.xsd.
test-method:: Validate the instance document against the commonClasses.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/isometadatatype/resolution
target:: /req/base/isometadatatype/resolution
test-purpose:: Verify that instance documents using the MD_Resolution XML elements validate against the XML schema specified in https://schemas.isotc211.org/19115/-1/mcc/1.3.0/resolution.xsd.
test-method:: Validate the instance document against the commonClasses.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====
