[conformance_class]
.AI_Task
====
[%metadata]
identifier:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/aitask
target:: /req/aitask
inherit:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/base/xmlbasetype
abstract-test:: /conf/aitask/task
abstract-test:: /conf/aitask/eotask
====

[abstract_test]
====
[%metadata]
identifier:: /conf/aitask/task
target:: /req/aitask/task
test-purpose:: Verify that instance documents using the AI_Task XML elements listed in <<table-ai-task-properties>> validate against the XML schema specified in http://schemas.opengis.net/trainingdml-ai/part3/1.0/ai_task.xsd.
test-method:: Validate the instance document against the ai_task.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/aitask/eotask
target:: /req/aitask/eotask
test-purpose:: Verify that instance documents using the AI_EOTask XML elements listed in <<table-ai-task-properties>> and <<table-ai-eotask-properties>> validate against the XML schema specified in http://schemas.opengis.net/trainingdml-ai/part3/1.0/ai_eoTask.xsd.
test-method:: Validate the instance document against the ai_eoTask.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====
