[conformance_class]
.AI_TrainingData
====
[%metadata]
identifier:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/aitrainingdata
target:: /req/aitrainingdata
inherit:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/base/xmlbasetype
inherit:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/base/isometadatatype
inherit:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/ailabel
inherit:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/ailabeling
inherit:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/aidataquality
abstract-test:: /conf/aitrainingdata/trainingdata
abstract-test:: /conf/aitrainingdata/trainingtypecode
abstract-test:: /conf/aitrainingdata/eotrainingdata
====

[abstract_test]
====
[%metadata]
identifier:: /conf/aitrainingdata/trainingdata
target:: /req/aitrainingdata/trainingdata
test-purpose:: Verify that instance documents using the AI_TrainingData XML elements listed in <<table-ai-trainingdata-properties>> validate against the XML schema specified in http://schemas.opengis.net/trainingdml-ai/part3/1.0/ai_trainingData.xsd.
test-method:: Validate the instance document against the ai_trainingData.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/aitrainingdata/trainingtypecode
target:: /req/aitrainingdata/trainingtypecode
test-purpose:: Verify that instance documents using the AI_TrainingTypeCode XML elements validate against the XML schema specified in http://schemas.opengis.net/trainingdml-ai/part3/1.0/ai_trainingTypeCode.xsd.
test-method:: Validate the instance document against the ai_trainingTypeCode.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/aitrainingdata/eotrainingdata
target:: /req/aitrainingdata/eotrainingdata
test-purpose:: Verify that instance documents using the AI_EOTrainingData XML elements listed in <<table-ai-trainingdata-properties>> and <<table-ai-eotrainingdata-properties>> validate against the XML schema specified in http://schemas.opengis.net/trainingdml-ai/part3/1.0/ai_eoTrainingData.xsd.
test-method:: Validate the instance document against the ai_eoTrainingData.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====
