[conformance_class]
.XML Base Type
====
[%metadata]
identifier:: http://www.opengis.net/spec/TrainingDML-AI-3/1.0/conf/base/xmlbasetype
target:: /req/base/xmlbasetype
abstract-test:: /conf/base/xmlbasetype/xml
abstract-test:: /conf/base/xmlbasetype/datetime
abstract-test:: /conf/base/xmlbasetype/namedvalue
abstract-test:: /conf/base/xmlbasetype/url
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/xmlbasetype/xml
target:: /req/base/xmlbasetype/xml
test-purpose:: Verify that the document is well-formed XML.
test-method:: Load the document in an XML validator. Pass if no errors reported. Fail otherwise.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/xmlbasetype/datetime
target:: /req/base/xmlbasetype/datetime
test-purpose:: Verify that XML instance documents claiming conformance to this specification contain valid DateTime values according to https://www.w3.org/TR/xmlschema11-2/#dateTime[Section 3.3.7], https://www.w3.org/TR/xmlschema11-2/#time[Section 3.3.8] or https://www.w3.org/TR/xmlschema11-2/#date[Section 3.3.9] of W3C XML Schema Definition Language (XSD) 1.1 Part 2: Datatypes.
test-method:: Inspect the instance document to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/xmlbasetype/namedvalue
target:: /req/base/xmlbasetype/namedvalue
test-purpose:: Verify that XML instance documents claiming conformance to this specification validate against the XML schema specified in http://schemas.opengis.net/trainingdml-ai/part3/1.0/namedValue.xsd.
test-method:: Validate the instance document against the namedValue.xsd schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the XML schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/xmlbasetype/url
target:: /req/base/xmlbasetype/url
test-purpose:: Verify that XML instance documents claiming conformance to this specification contain valid URL values according to the W3C definition of anyURI, which represents an Internationalized Resource Identifier Reference. An anyURI value can be absolute or relative and may have an optional fragment identifier.
test-method:: Inspect the instance document to verify the above requirement.
====
