[bibliography]
== References

The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

* [[[RFC2046,IETF RFC 2046]]] IETF, _Multipurpose Internet Mail Extensions (MIME) Part Two: Media Types_, RFC 2046, 1996. https://www.ietf.org/rfc/rfc2046.txt

* [[[ISO19101-1:2014,ISO 19101-1:2014]]], ISO 19101-1:2014 Geographic information — Reference model — Part 1: Fundamentals, 2014

* [[[ISO19103:2024,ISO 19103:2024]]], ISO 19103:2024 Geographic
information — Conceptual schema language, 2024

* [[[ISO19115-1:2014,ISO 19115-1:2014]]], ISO 19115-1:2014 Geographic
information — Metadata — Part 1: Fundamentals, 2014

* [[[ISO19156:2023,ISO 19156:2023]]], ISO 19156:2023 Geographic information — Observations, measurements and samples, 2023

* [[[ISO19157-1,ISO 19157-1]]], ISO 19157-1 Geographic
information — Data quality — Part 1: General requirements, 2023
