[conformance_class]
.AI_Task
====
[%metadata]
identifier:: http://www.opengis.net/spec/TrainingDML-AI-2/1.0/conf/aitask
target:: /req/aitask
inherit:: http://www.opengis.net/spec/TrainingDML-AI-2/1.0/conf/base/jsonbasetype
abstract-test:: /conf/aitask/task
abstract-test:: /conf/aitask/eotask
====

[abstract_test]
====
[%metadata]
identifier:: /conf/aitask/task
target:: /req/aitask/task
test-purpose:: Verify that instance documents using the AI_Task JSON objects listed in <<table-ai-task-properties>> validate against the JSON schema specified in http://schemas.opengis.net/trainingdml-ai/part2/1.0/ai_task.json.
test-method:: Validate the instance document against the ai_task.json schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the JSON schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/aitask/eotask
target:: /req/aitask/eotask
test-purpose:: Verify that instance documents using the AI_EOTask JSON objects listed in <<table-ai-task-properties>> and <<table-ai-eotask-properties>> validate against the JSON schema specified in http://schemas.opengis.net/trainingdml-ai/part2/1.0/ai_eoTask.json.
test-method:: Validate the instance document against the ai_eoTask.json schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the JSON schema specification.
====
