[conformance_class]
.JSON Base Type
====
[%metadata]
identifier:: http://www.opengis.net/spec/TrainingDML-AI-2/1.0/conf/base/jsonbasetype
target:: /req/base/jsonbasetype
abstract-test:: /conf/base/jsonbasetype/json
abstract-test:: /conf/base/jsonbasetype/datetime
abstract-test:: /conf/base/jsonbasetype/namedvalue
abstract-test:: /conf/base/jsonbasetype/url
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/jsonbasetype/json
target:: /req/base/jsonbasetype/json
test-purpose:: Verify that the document is well-formed JSON.
test-method:: Load the document in a JSON validator. Pass if no errors reported. Fail otherwise.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/jsonbasetype/datetime
target:: /req/base/jsonbasetype/datetime
test-purpose:: Verify that JSON instance documents claiming conformance to this specification contain valid DateTime values according to Date and Time on the Internet: Timestamps [https://datatracker.ietf.org/doc/html/rfc3339#section-5.6[RFC 3339 Section 5.6]].
test-method:: Inspect the instance document to verify the above requirement.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/jsonbasetype/namedvalue
target:: /req/base/jsonbasetype/namedvalue
test-purpose:: Verify that JSON instance documents claiming conformance to this specification validate against the JSON schema specified in  http://schemas.opengis.net/trainingdml-ai/part2/1.0/namedValue.json.
test-method:: Validate the instance document against the namedValue.json schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the JSON schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/jsonbasetype/url
target:: /req/base/jsonbasetype/url
test-purpose:: Verify that JSON instance documents claiming conformance to this specification contain valid URL values according to Uniform Resource Identifier (URI): Generic Syntax [https://datatracker.ietf.org/doc/html/rfc3986#section-4.1[RFC 3986 Section 4.1]]. A URL value can be absolute or relative and may have an optional fragment identifier.
test-method:: Inspect the instance document to verify the above requirement.
====
