[conformance_class]
.ISO Metadata Type
====
[%metadata]
identifier:: http://www.opengis.net/spec/TrainingDML-AI-2/1.0/conf/base/isometadatatype
target:: /req/base/isometadatatype
abstract-test:: /conf/base/isometadatatype/band
abstract-test:: /conf/base/isometadatatype/extent
abstract-test:: /conf/base/isometadatatype/citation
abstract-test:: /conf/base/isometadatatype/scope
abstract-test:: /conf/base/isometadatatype/referencesystem
abstract-test:: /conf/base/isometadatatype/lineage
abstract-test:: /conf/base/isometadatatype/resolution
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/isometadatatype/band
target:: /req/base/isometadatatype/band
test-purpose:: Verify that instance documents using the MD_Band JSON objects validate against the JSON schema specified in  http://schemas.opengis.net/trainingdml-ai/part2/1.0/md_band.json.
test-method:: Validate the instance document against the md_band.json schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the JSON schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/isometadatatype/extent
target:: /req/base/isometadatatype/extent
test-purpose:: Verify that instance documents using the EX_Extent JSON objects validate against the JSON schema specified in  http://schemas.opengis.net/trainingdml-ai/part2/1.0/ex_extent.json.
test-method:: Validate the instance document against the ex_extent.json schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the JSON schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/isometadatatype/citation
target:: /req/base/isometadatatype/citation
test-purpose:: Verify that instance documents using the CI_Citation JSON objects validate against the JSON schema specified in  http://schemas.opengis.net/trainingdml-ai/part2/1.0/ci_citation.json.
test-method:: Validate the instance document against the ci_citation.json schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the JSON schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/isometadatatype/scope
target:: /req/base/isometadatatype/scope
test-purpose:: Verify that instance documents using the MD_Scope JSON objects validate against the JSON schema specified in  http://schemas.opengis.net/trainingdml-ai/part2/1.0/md_scope.json.
test-method:: Validate the instance document against the md_scope.json schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the JSON schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/isometadatatype/referencesystem
target:: /req/base/isometadatatype/referencesystem
test-purpose:: Verify that instance documents using the MD_ReferenceSystem JSON objects validate against the JSON schema specified in http://schemas.opengis.net/trainingdml-ai/part2/1.0/md_referenceSystem.json.
test-method:: Validate the instance document against the md_referenceSystem.json schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the JSON schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/isometadatatype/lineage
target:: /req/base/isometadatatype/lineage
test-purpose:: Verify that instance documents using the LI_Lineage JSON objects validate against the JSON schema specified in http://schemas.opengis.net/trainingdml-ai/part2/1.0/li_lineage.json.
test-method:: Validate the instance document against the li_lineage.json schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the JSON schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/base/isometadatatype/resolution
target:: /req/base/isometadatatype/resolution
test-purpose:: Verify that instance documents using the MD_Resolution JSON objects validate against the JSON schema specified in http://schemas.opengis.net/trainingdml-ai/part2/1.0/md_resolution.json.
test-method:: Validate the instance document against the md_resolution.json schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the JSON schema specification.
====
