[conformance_class]
.AI_Label
====
[%metadata]
identifier:: http://www.opengis.net/spec/TrainingDML-AI-2/1.0/conf/ailabel
target:: /req/ailabel
inherit:: http://www.opengis.net/spec/TrainingDML-AI-2/1.0/conf/base/jsonbasetype
inherit:: http://www.opengis.net/spec/TrainingDML-AI-2/1.0/conf/base/geospatialtype
abstract-test:: /conf/ailabel/label
abstract-test:: /conf/ailabel/scenelabel
abstract-test:: /conf/ailabel/objectlabel
abstract-test:: /conf/ailabel/pixellabel
abstract-test:: /conf/ailabel/imageformatcode
====

[abstract_test]
====
[%metadata]
identifier:: /conf/ailabel/label
target:: /req/ailabel/label
test-purpose:: Verify that instance documents using the AI_Label JSON objects listed in <<table-ai-label-properties>> validate against the JSON schema specified in http://schemas.opengis.net/trainingdml-ai/part2/1.0/ai_label.json.
test-method:: Validate the instance document against the ai_label.json schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the JSON schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/ailabel/scenelabel
target:: /req/ailabel/scenelabel
test-purpose:: Verify that instance documents using the AI_SceneLabel JSON objects listed in <<table-ai-scenelabel-properties>> validate against the JSON schema specified in http://schemas.opengis.net/trainingdml-ai/part2/1.0/ai_sceneLabel.json.
test-method:: Validate the instance document against the ai_sceneLabel.json schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the JSON schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/ailabel/objectlabel
target:: /req/ailabel/objectlabel
test-purpose:: Verify that instance documents using the AI_ObjectLabel JSON objects listed in <<table-ai-objectlabel-properties>> validate against the JSON schema specified in http://schemas.opengis.net/trainingdml-ai/part2/1.0/ai_objectLabel.json.
test-method:: Validate the instance document against the ai_objectLabel.json schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the JSON schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/ailabel/pixellabel
target:: /req/ailabel/pixellabel
test-purpose:: Verify that instance documents using the AI_PixelLabel JSON objects listed in <<table-ai-pixellabel-properties>> validate against the JSON schema specified in http://schemas.opengis.net/trainingdml-ai/part2/1.0/ai_pixelLabel.json.
test-method:: Validate the instance document against the ai_pixelLabel.json schema to verify the above requirement. The process may be using an appropriate software tool for validation or be a manual process that checks all definitions from the JSON schema specification.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/ailabel/imageformatcode
target:: /req/ailabel/imageformatcode
test-purpose:: Verify that instance documents using the AI_ImageFormatCode JSON objects conform to the requirements specified by the Multipurpose Internet Mail Extensions (MIME) Part Two: Media Types https://www.ietf.org/rfc/rfc2046.txt[RFC 2046].
test-method:: Inspect the instance document to verify the above requirement.
====
