[width="100%",cols="20%,80%",options="header,unnumbered"]
|===
2+|*Requirements class* 
2+|/req/aitrainingdataset
|Dependency |JSON
|Dependency |/req/base/jsonbasetype
|Dependency |/req/base/isometadatatype
|Dependency |/req/aitrainingdata
|Dependency |/req/aitask
|Dependency |/req/ailabeling
|Dependency |/req/aidataquality
|Dependency |/req/aitdchangeset
|Requirement 14|/req/aitrainingdataset/trainingdataset
|Requirement 15|/req/aitrainingdataset/metricsinliterature
|Requirement 16|/req/aitrainingdataset/eotrainingdataset
|===

The AI_TrainingDataset object is encoded as a JSON object with properties shown in <<table-ai-trainingdataset-properties>>.

[width="100%",cols="20%,80%",options="unnumbered"]
|===
|Requirement 14
a|/req/aitrainingdataset/trainingdataset

Each AI_TrainingDataset object SHALL implement the Mandatory properties shown in <<table-ai-trainingdataset-properties>>.
|===

[[table-ai-trainingdataset-properties]]
.AI_TrainingDataset properties
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|JSON Property |Definition |Data type and values |Obligation
|type |Type of the training dataset. |"AI_AbstractTrainingDataset" |Mandatory
|id |Identification of the AI training dataset. |CharacterString [1..1] |Mandatory
|doi |Digital object identifier of the AI training dataset. |CharacterString [0..1] |Optional
|scope |Description of the scope of the training dataset. |MD_Scope [0..1] |Optional
|name |Name of the AI training dataset. |CharacterString [1..1] |Mandatory
|description |Description of the AI training dataset. |CharacterString [1..1] |Mandatory
|version |Version number of the AI training dataset. |CharacterString [0..1] |Optional
|amountOfTrainingData |Total number of training samples in the AI training dataset. |Int [0..1] |Optional
|createdTime |Time when the AI training dataset was created. |DateTime [0..1] |Optional
|updatedTime |Time when the AI training dataset was updated. |DateTime [0..1] |Optional
|license |License description of the AI training dataset. |CharacterString [1..1] |Mandatory
|providers |People or organizations who provide the AI training dataset. |CharacterString [0..*] |Optional
|keywords |Keywords of the AI training dataset. |CharacterString [0..*] |Optional
|metricsInLIT |Results of performance metrics achieved by AI/ML algorithms in the peer-reviewed literature. |AI_MetricsInLiterature [0..*] |Optional
|statisticsInfo |Statistical results for training samples in each class. |NamedValue [0..*] |Optional
|dataSources |Citation for the data sources. |CI_Citation [0..*] |Optional
|numberOfClasses |Total number of classes in the AI training dataset. |Int [0..1] |Optional
|classificationScheme |Classification scheme for classes used in the AI training dataset. |CharacterString [0..1] |Optional
|classes |Classes used in the AI training dataset. |NamedValue [0..*] |Optional
|extent |Spatial extent of the training dataset. |EX_Extent [0..1] |Optional
|referenceSystem |Reference system of the training dataset. |MD_ReferenceSystem [0..1] |Optional
|lineage |Information about the provenance, source(s), and/or the production process(es) applied to the training dataset.|LI_Lineage [0..*] |Optional
|tasks |Task description of the training dataset. |AI_Task [1..*] |Mandatory
|labeling |Provenance information of how the training dataset is labeled. |AI_Labeling [0..*] |Optional
|quality |Quality information of the training dataset. |DataQuality [0..*] |Optional
|changesets |Changeset between two versions of the training dataset. |AI_TDChangeset [0..*] |Optional
|data |Training data in the training dataset. |AI_AbstractTrainingData [1..*] |Mandatory
|===

Example:

[source%unnumbered,json]
----
{
  "type": "AI_AbstractTrainingDataset",
  "id": "whu_rs19",
  "name": "WHU-RS19",
  "description": "Wuhan University-Remote Sensing 19 Categories (WHU-RS19) has 19 classes of remote sensing images scenes obtained from Google Earth",
  "license": "CC BY-SA 4.0",
  "amountOfTrainingData": 1013,
  "createdTime": "2010-01-01",
  "providers": [
    "Wuhan University"
  ],
  "keywords": [
    "Remote Sensing",
    "Scene Classification"
  ],
  "numberOfClasses": 19,
  "classes": [
    {
      "key": "Airport",
      "value": null
    },
    {
      "key": "Beach",
      "value": null
    },
    {
      "key": "Bridge",
      "value": null
    },
    {
      "key": "Commercial",
      "value": null
    },
    {
      "key": "Desert",
      "value": null
    },
    {
      "key": "Farmland",
      "value": null
    },
    {
      "key": "footballField",
      "value": null
    },
    {
      "key": "Forest",
      "value": null
    },
    {
      "key": "Industrial",
      "value": null
    },
    {
      "key": "Meadow",
      "value": null
    },
    {
      "key": "Mountain",
      "value": null
    },
    {
      "key": "Park",
      "value": null
    },
    {
      "key": "Parking",
      "value": null
    },
    {
      "key": "Pond",
      "value": null
    },
    {
      "key": "Port",
      "value": null
    },
    {
      "key": "railwayStation",
      "value": null
    },
    {
      "key": "Residential",
      "value": null
    },
    {
      "key": "River",
      "value": null
    },
    {
      "key": "Viaduct",
      "value": null
    }
  ],
  "extent": [
    -180,
    -90,
    180,
    90
  ],
  "referenceSystem": {
    "referenceSystemIdentifier": "EPSG:4326"
  },
  "tasks": [
    {
      "type": "AI_EOTask",
      "id": "whu_rs19-task",
      "description": "Structural high-resolution satellite image indexing",
      "taskType": "Scene Classification"
    }
  ],
  "data": [
    {
      "type": "AI_EOTrainingData",
      "id": "airport_01",
      "dataSources": [
        {
          "title": "googleEarth"
        }
      ],
      "dataURL": [
        "image/Airport/airport_01.jpg"
      ],
      "labels": [
        {
          "type": "AI_SceneLabel",
          "class": "Airport"
        }
      ]
    },
    …
  ]
}
----

If the optional element AI_MetricsInLiterature is specified, this element is encoded as JSON object with properties as shown in <<table-ai-metricsinliterature-properties>>.

[width="100%",cols="20%,80%",options="unnumbered"]
|===
|Requirement 15
a|/req/aitrainingdataset/metricsinliterature

Each AI_MetricsInLiterature value SHALL implement the Mandatory properties shown in <<table-ai-metricsinliterature-properties>>.
|===

[[table-ai-metricsinliterature-properties]]
.AI_MetricsInLiterature properties
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|JSON Property |Definition |Data type and values |Obligation
|doi |Digital object identifier of the peer-reviewed literature. |CharacterString [1..1] |Mandatory
|algorithm |AI/ML algorithms used in the peer-reviewed literature. |CharacterString [0..1] |Optional
|metrics |Metrics and results of AI/ML algorithms in the peer-reviewed literature. |NamedValue [1..*] |Mandatory
|===

Example:

[source%unnumbered,json]
----
{
  "doi": "10.1109/TGRS.2019.2917161",
  "algorithm": "FACNN",
  "metrics": [
    {
      "key": "Overall Accuracy",
      "value": 0.9881
    }
  ]
}
----

The AI_EOTrainingDataset object is encoded as a JSON object with properties shown in <<table-ai-trainingdataset-properties>> and <<table-ai-eotrainingdataset-properties>>.

[width="100%",cols="20%,80%",options="unnumbered"]
|===
|Requirement 16
a|/req/aitrainingdataset/eotrainingdataset

Each AI_EOTrainingDataset object SHALL implement the Mandatory properties both shown in <<table-ai-trainingdataset-properties>> and <<table-ai-eotrainingdataset-properties>>.
|===

[[table-ai-eotrainingdataset-properties]]
.AI_EOTrainingDataset properties
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|JSON Property |Definition |Data type and values |Obligation
|type |Type of the training dataset. |"AI_EOTrainingDataset" |Mandatory
|bands |Description of the image bands used in the EO training dataset. |MD_Band [0..*] |Optional
|imageSize |Size of the images used in the EO training dataset. |CharacterString [0..1] |Optional
|===

Example:

[source%unnumbered,json]
----
{
  "type": "AI_EOTrainingDataset",
  "id": "whu_rs19",
  "name": "WHU-RS19",
  "description": "Wuhan University-Remote Sensing 19 Categories (WHU-RS19) has 19 classes of remote sensing images scenes obtained from Google Earth",
  "license": "CC BY-SA 4.0",
  "amountOfTrainingData": 1013,
  "createdTime": "2010-01-01",
  "providers": [
    "Wuhan University"
  ],
  "keywords": [
    "Remote Sensing",
    "Scene Classification"
  ],
  "numberOfClasses": 19,
  "extent": [
    -180,
    -90,
    180,
    90
  ],
  "referenceSystem": {
    "referenceSystemIdentifier": "EPSG:4326"
  },
  "bands": [
    {
      "name": [
        {
          "code": "red"
        }
      ]
    },
    {
      "name": [
        {
          "code": "green"
        }
      ]
    },
    {
      "name": [
        {
          "code": "blue"
        }
      ]
    }
  ],
  "imageSize": "6000x7600",
  "classes": [
    {
      "key": "Airport",
      "value": null
    },
    {
      "key": "Beach",
      "value": null
    },
    {
      "key": "Bridge",
      "value": null
    },
    {
      "key": "Commercial",
      "value": null
    },
    {
      "key": "Desert",
      "value": null
    },
    {
      "key": "Farmland",
      "value": null
    },
    {
      "key": "footballField",
      "value": null
    },
    {
      "key": "Forest",
      "value": null
    },
    {
      "key": "Industrial",
      "value": null
    },
    {
      "key": "Meadow",
      "value": null
    },
    {
      "key": "Mountain",
      "value": null
    },
    {
      "key": "Park",
      "value": null
    },
    {
      "key": "Parking",
      "value": null
    },
    {
      "key": "Pond",
      "value": null
    },
    {
      "key": "Port",
      "value": null
    },
    {
      "key": "railwayStation",
      "value": null
    },
    {
      "key": "Residential",
      "value": null
    },
    {
      "key": "River",
      "value": null
    },
    {
      "key": "Viaduct",
      "value": null
    }
  ],
  "tasks": [
    {
      "type": "AI_EOTask",
      "id": "whu_rs19-task",
      "description": "Structural high-resolution satellite image indexing",
      "taskType": "Scene Classification"
    }
  ],
  "data": [
    {
      "type": "AI_EOTrainingData",
      "id": "airport_01",
      "dataSources": [
        {
          "title": "googleEarth"
        }
      ],
      "dataURL": [
        "image/Airport/airport_01.jpg"
      ],
      "labels": [
        {
          "type": "AI_SceneLabel",
          "class": "Airport"
        }
      ]
    },
    …
  ]
}
----
