[width="100%",cols="20%,80%",options="header,unnumbered"]
|===
2+|*Requirements class* 
2+|/req/aitask
|Dependency |XML
|Dependency |/req/base/xmlbasetype
|Requirement 20|/req/aitask/task
|Requirement 21|/req/aitask/eotask
|===

The AI_Task object is encoded as an XML element with properties as shown in <<table-ai-task-properties>>.

[width="100%",cols="20%,80%",options="unnumbered"]
|===
|Requirement 20
a|/req/aitask/task

Each AI_Task object SHALL implement the Mandatory properties shown in <<table-ai-task-properties>>.
|===

[[table-ai-task-properties]]
.AI_Task properties
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|XML Property |Definition |Data type and values |Obligation
|type |Type of the task object. |"AI_AbstractTask" |Mandatory
|id |Identification of the task. |CharacterString [1..1] |Mandatory
|datasetId |Identification of the training dataset the training sample belongs to. |CharacterString [0..1] |Optional
|description |Description of the AI task. |CharacterString [0..1] |Optional
|===

Example:

[source%unnumbered,xml]
----
   <type>AI_AbstractTask</type>
   <id>image-indexing-task</id>
   <description>Structural high-resolution satellite image indexing</description>
----

The AI_EOTask object is encoded as an XML element with properties both shown in <<table-ai-task-properties>> and <<table-ai-eotask-properties>>.

[width="100%",cols="20%,80%",options="unnumbered"]
|===
|Requirement 21
a|/req/aitask/eotask

Each AI_EOTask object SHALL implement the Mandatory properties shown in <<table-ai-task-properties>> and <<table-ai-eotask-properties>>.
|===

[[table-ai-eotask-properties]]
.AI_EOTask properties
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|XML Property |Definition |Data type and values |Obligation
|type |Type of the task object. |"AI_EOTask" |Mandatory
|taskType |Type of the EO task. |CharacterString [1..1] |Mandatory
|===

Example:

[source%unnumbered,xml]
----
   <type>AI_EOTask</type>
   <id>image-indexing-task</id>
   <description>Structural high-resolution satellite image indexing</description>
   <taskType>Scene Classification</taskType>
----
