[width="100%",cols="20%,80%",options="header,unnumbered"]
|===
2+|*Requirements class* 
2+|/req/aitrainingdata
|Dependency |XML
|Dependency |/req/base/xmlbasetype
|Dependency |/req/base/isometadatatype
|Dependency |/req/ailabel
|Dependency |/req/ailabeling
|Dependency |/req/aidataquality
|Requirement 17|/req/aitrainingdata/trainingdata
|Requirement 18|/req/aitrainingdata/trainingtypecode
|Requirement 19|/req/aitrainingdata/eotrainingdata
|===

The AI_TrainingData object is encoded as an XML element with properties shown in <<table-ai-trainingdata-properties>>.

[width="100%",cols="20%,80%",options="unnumbered"]
|===
|Requirement 17
a|/req/aitrainingdata/trainingdata

Each AI_TrainingData object SHALL implement the Mandatory properties shown in <<table-ai-trainingdata-properties>>.
|===

[[table-ai-trainingdata-properties]]
.AI_TrainingData properties
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|XML Property |Definition |Data type and values |Obligation
|type |Type of the training sample. |"AI_AbstractTrainingData" |Mandatory
|id |Identification of an individual AI training sample. |CharacterString [1..1] |Mandatory
|datasetId |Identification of the training dataset that the training sample belongs to. |CharacterString [0..1] |Optional
|trainingType |Training type of the individual AI training sample. |AI_TrainingTypeCode [0..1] |Optional
|numberOfLabels |Total number of labels in the individual AI training sample. |Int [0..1] |Optional
|dataSources |Citation of inputs to prepare a training sample. |CI_Citation [0..*] |Optional
|extent |Spatial extent of the individual training sample. |EX_Extent [0..1] |Optional
|dataTime |Date and time at which the geospatial data were obtained. |DateTime [0..*] |Optional
|lineage |Information about the provenance, source(s), and/or the production process(es) applied to the training sample. |LI_Lineage [0..*] |Optional
|labels |Labels in the training data. |AI_Label [0..*] |Optional
|labeling |Provenance information of how the training data is labeled. |AI_Labeling [0..*] |Optional
|quality |Quality information of the training data. |DataQuality [0..*] |Optional
|===

Example:

[source%unnumbered,xml]
----
   <type>AI_AbstractTrainingData</type>
   <id>airport_01</id>
   <dataSources>
      <cit:title>
         <gco:CharacterString>googleEarth</gco:CharacterString>
      </cit:title>
   </dataSources>
   <dataURL>image/Airport/airport_01.jpg</dataURL>
   <extent>
      <gex:geographicElement>
         <gex:EX_GeographicBoundingBox>
            <gex:westBoundLongitude>
               <gco:Decimal>-171.76409</gco:Decimal>
            </gex:westBoundLongitude>
            <gex:eastBoundLongitude>
               <gco:Decimal>-171.56578</gco:Decimal>
            </gex:eastBoundLongitude>
            <gex:southBoundLatitude>
               <gco:Decimal>-14.42443</gco:Decimal>
            </gex:southBoundLatitude>
            <gex:northBoundLatitude>
               <gco:Decimal>-14.32568</gco:Decimal>
            </gex:northBoundLatitude>
         </gex:EX_GeographicBoundingBox>
      </gex:geographicElement>
   </extent>
   <dataTime>2002-05-30T09:30:10Z</dataTime>
   <labels>
      <type>AI_SceneLabel</type>
      <class>Airport</class>
   </labels>
----

The AI_TrainingTypeCode is encoded as a text string whose value is one of “training”, “validation”, “test” or “retraining”.

[width="100%",cols="20%,80%",options="unnumbered"]
|===
|Requirement 18
a|/req/aitrainingdata/trainingtypecode

Each AI_TrainingTypeCode value SHALL be a text string whose value is one of “training”, “validation”, “test” or “retraining”.
|===

Examples:

[source%unnumbered,text]
----
 a) "training"
 b) "validation"
 c) "test"
 d) "retraining"
----

The AI_EOTrainingData object is encoded as an XML element with properties both shown in <<table-ai-trainingdata-properties>> and <<table-ai-eotrainingdata-properties>>.

[width="100%",cols="20%,80%",options="unnumbered"]
|===
|Requirement 19
a|/req/aitrainingdata/eotrainingdata

Each AI_EOTrainingData object SHALL implement the Mandatory properties as defined in <<table-ai-trainingdata-properties>> and <<table-ai-eotrainingdata-properties>>.
|===

[[table-ai-eotrainingdata-properties]]
.AI_EOTrainingData properties
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|XML Property |Definition |Data type and values |Obligation
|type |Type of the EO training data. |"AI_EOTrainingData" |Mandatory
|spatialResolution |Spatial resolution of the individual EO training sample. |MD_Resolution [0..1] |Optional
|dataURL |URLs of the EO data, including both relative and absolute paths, which can encompass local paths, network addresses, and more. |URI [1..*] |Mandatory
|===

Example:

[source%unnumbered,xml]
----
   <type>AI_EOTrainingData</type>
   <id>airport_01</id>
   <dataSources>
      <cit:title>
         <gco:CharacterString>googleEarth</gco:CharacterString>
      </cit:title>
   </dataSources>
   <extent>
      <gex:geographicElement>
         <gex:EX_GeographicBoundingBox>
            <gex:westBoundLongitude>
               <gco:Decimal>-171.76409</gco:Decimal>
            </gex:westBoundLongitude>
            <gex:eastBoundLongitude>
               <gco:Decimal>-171.56578</gco:Decimal>
            </gex:eastBoundLongitude>
            <gex:southBoundLatitude>
               <gco:Decimal>-14.42443</gco:Decimal>
            </gex:southBoundLatitude>
            <gex:northBoundLatitude>
               <gco:Decimal>-14.32568</gco:Decimal>
            </gex:northBoundLatitude>
         </gex:EX_GeographicBoundingBox>
      </gex:geographicElement>
   </extent>
   <spatialResolution>
   <mri:MD_Resolution>
      <gco:Distance uom="meter">10</gco:Distance>
   </mri:MD_Resolution>
   </spatialResolution>
   <dataTime>2002-05-30T09:30:10Z</dataTime>
   <dataURL>image/Airport/airport_01.jpg</dataURL>
   <labels>
      <type>AI_SceneLabel</type>
      <class>Airport</class>
   </labels>
----
