[width="100%",cols="20%,80%",options="header,unnumbered"]
|===
2+|*Requirements class* 
2+|/req/base/xmlbasetype 
|Dependency |XML
|Requirement 1|/req/base/xmlbasetype/xml
|Requirement 2|/req/base/xmlbasetype/datetime
|Requirement 3|/req/base/xmlbasetype/namedvalue
|Requirement 4|/req/base/xmlbasetype/url
|===

The first requirement is that a TrainingDML-AI XML document is a valid XML document.

[width="100%",cols="20%,80%",options="unnumbered"]
|===
|Requirement 1
a|/req/base/xmlbasetype/xml

An instance SHALL be a conformant XML document, as defined by W3C Recommendation
|===

XML has a limited range of built-in types (https://www.w3.org/TR/xmlschema11-2/). The following requirements provide standard XML representations of additional types required across all requirements within this specification.

The DateTime is encoded as an XML element defined as one of three elements of type "date", "time", "dateTime".

[width="100%",cols="20%,80%",options="unnumbered"]
|===
|Requirement 2
a|/req/base/xmlbasetype/datetime

Each DateTime value SHALL be encoded as a text string defined in https://www.w3.org/TR/xmlschema11-2/#dateTime[Section 3.3.7], https://www.w3.org/TR/xmlschema11-2/#time[Section 3.3.8] or https://www.w3.org/TR/xmlschema11-2/#date[Section 3.3.9] of W3C XML Schema Definition Language (XSD) 1.1 Part 2: Datatypes.

The specification of date and time in any XML encoding of training set data SHALL be specified in UTC.
|===

Examples:

[source%unnumbered,text]
----
 a)   "2002-05-30T09:30:10Z"
 b)   "2002-09-24"
----

The NamedValue is encoded as an XML element with two elements named “key” and “value”. Typically, the "key" element represents a unique identifier or name for the value being described, while the "value" element contains the actual data associated with that identifier. The "key" element is an open field allowing for arbitrary keys to be used. The "value" element may be any types.

[width="100%",cols="20%,80%",options="unnumbered"]
|===
|Requirement 3
a|/req/base/xmlbasetype/namedvalue

Each NamedValue value SHALL be encoded as an XML element with elements "key" and "value", while the type of "key" is CharacterString.
|===

Examples:

[source%unnumbered,xml]
----
 a) <key>forest</key>
    <value>RGB(0,255,255)</value>
 b) <key>precision</key>
    <value>0.8</value>
----

The URL is encoded as an XML element defined as the type of “anyURI”.

[width="100%",cols="20%,80%",options="unnumbered"]
|===
|Requirement 4
a|/req/base/xmlbasetype/url

Each URL value SHALL be encoded as a text string defined in Section 3.3.17 of W3C XML Schema Definition Language (XSD) 1.1 Part 2: Datatypes.
|===

Examples:

[source%unnumbered,text]
----
 a) "http://www.opengeospatial.org"
 b) "/file.txt"
 c) "./dataset/file.txt"
----
