[width="100%",cols="20%,80%",options="header,unnumbered"]
|===
2+|*Requirements class* 
2+|/req/aidataquality
|Dependency |XML
|Dependency |/req/base/xmlbasetype
|Dependency |/req/base/isometadatatype
|Dependency |/req/base/isoqualitytype
|Requirement 31|/req/aidataquality/classbalancedegree
|===

The AI_ClassBalanceDegree object is encoded as an XML element with properties as shown in <<table-ai-classbalancedegree-properties>>.

[width="100%",cols="20%,80%",options="unnumbered"]
|===
|Requirement 31
a|/req/aidataquality/classbalancedegree

Each AI_ClassBalanceDegree object SHALL implement the Mandatory properties as shown in <<table-ai-classbalancedegree-properties>>.
|===

[[table-ai-classbalancedegree-properties]]
.AI_ClassBalanceDegree properties
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|XML Property |Definition |Data type and values |Obligation
|type |Type of the class balance degree object. |"AI_ClassBalanceDegree" |Mandatory
|measure |Reference to measure used. |MeasureReference [1..1] |Mandatory
|evaluationMethod |Evaluation information. |EvaluationMethod [1..*] |Mandatory
|result |Value obtained from applying a data quality measure. |QualityResult [1..*] |Mandatory
|===

Example:

[source%unnumbered,xml]
----
  <type>AI_ClassBalanceDegree</type>
  <measure>
    <measureDescription>
      Balance degree of label classes
    </measureDescription>
  </measure>
  <evaluationMethod>
    <evaluationMethodDescription>
      Counting the number of training samples belonging to each class and calculating the balance degree
    </evaluationMethodDescription>
  </evaluationMethod>
  <result>
    <quantitativeResult>
        <value>
          93.5
        </value>
        <valueUnit>
          %
        </valueUnit>
    </quantitativeResult>
  </result>
----
