[abstract]
== Abstract

The OGC Training Data Markup Language for Artificial Intelligence (TrainingDML-AI) Part 3: XML Encoding Standard defines requirements for encoding AI training datasets as Extensible Markup Language (XML). XML is a widely utilized format for encoding data in various applications. It employs a markup structure where data is enclosed in tags represented by opening and closing elements. These elements can have attributes and may contain nested elements, allowing for a hierarchical representation of structured information. TrainingDML-AI Part 3 is based on the OGC Training Data Markup Language for Artificial Intelligence (TrainingDML-AI) Part 1: Conceptual Model Standard.

== Preface

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

== Security considerations

No security considerations have been made for this Standard.

== Submitters

All questions regarding this submission should be directed to the editors or the submitters:

[options="header"]
|===
|Name |Affiliation
|Peng Yue |Wuhan University
|Ruixiang Liu |Wuhan University
|Kaixuan Wang |Wuhan University
|Haoru Wu |Wuhan University
|Boyi Shangguan |Luoyao Information Technology Co., Ltd
|Samantha Lavender |Pixalytics Ltd
|Jim Antonisse |WiSC Enterprises
|Liping Di |George Mason University
|Eugene Yu |George Mason University
|Danielle Ziébelin |Laboratoire d’Informatique de Grenoble
|Liangcun Jiang |Wuhan University of Technology
|Lei Hu |Hubei University
|Mingda Zhang |Hubei University
|Kai Yan |Chongqing Changan Zhitu Technology Co., Ltd
|===

== Acknowledgments

Thanks to the members of the TrainingDML-AI Standards Working Group of the OGC as well as all contributors of change requests and comments. In particular: Scott Simmons, Carl Reed, Sam Meek, Yongyi Mi, Chenxiao Zhang, Zhipeng Cao, Shuaiqi Liu, Ming Zhao, Hanwen Xu, Haipeng Deng, Baoxin Teng.
